name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: "Unique build ID"
        required: true
        type: string

      zip_path:
        description: "Path of project ZIP"
        required: true
        type: string

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Show ZIP
        run: |
          echo "Build ID: ${{ inputs.build_id }}"
          echo "ZIP: ${{ inputs.zip_path }}"

          ls -lh "${{ inputs.zip_path }}"

      - name: Extract project
        run: |
          rm -rf project
          mkdir -p project

          unzip -q "${{ inputs.zip_path }}" -d project

          echo "=== Project contents ==="
          find project -maxdepth 2 -type f | head -100

      - name: Detect Android project
        run: |
          echo "Searching for Gradle project..."

          find project \
            -name "gradlew" \
            -o -name "build.gradle" \
            -o -name "build.gradle.kts" \
            -o -name "settings.gradle" \
            -o -name "settings.gradle.kts"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check Flutter project
        working-directory: project
        run: |
          echo "=== Current directory ==="
          pwd

          echo "=== Files ==="
          ls -lah

          if [ ! -f "pubspec.yaml" ]; then
            echo "ERROR: pubspec.yaml tidak ditemukan."
            echo ""
            echo "Kemungkinan struktur ZIP memiliki folder tambahan."
            echo "Contoh:"
            echo "project/project/pubspec.yaml"
            exit 1
          fi

      - name: Flutter dependencies
        working-directory: project
        run: |
          flutter pub get

      - name: Build APK
        working-directory: project
        run: |
          flutter build apk --release

      - name: Find APK
        run: |
          echo "=== APK files ==="

          find project \
            -type f \
            -name "*.apk" \
            -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ inputs.build_id }}
          path: project/build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
